/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

description = "XML serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde :: XML"
extra["moduleName"] = "aws.smithy.kotlin.runtime.serde.xml"

val slf4jVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":runtime:serde"))
            }
        }

        all {
            languageSettings.optIn("aws.smithy.kotlin.runtime.InternalApi")
        }
    }
}
