/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

description = "XML serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde :: XML"
extra["moduleName"] = "aws.smithy.kotlin.runtime.serde.xml"

val xmlpullVersion: String by project
val xpp3Version: String by project
val slf4jVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":runtime:serde"))
                implementation(project(":runtime:logging"))
            }
        }
        jvmMain {
            dependencies {
                implementation("xmlpull:xmlpull:$xmlpullVersion")
                // https://mvnrepository.com/artifact/org.ogce/xpp3
                implementation("org.ogce:xpp3:$xpp3Version")
            }
        }
        jvmTest {
            dependencies {
                implementation("org.slf4j:slf4j-simple:$slf4jVersion")
                implementation("org.slf4j:slf4j-api:$slf4jVersion")
            }
        }
    }
}
