/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

description = "Serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde"
extra["moduleName"] = "aws.smithy.kotlin.runtime.serde"


kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":runtime:runtime-core"))
                api(project(":runtime:utils"))
            }
        }
    }
}

subprojects {
    kotlin {
        sourceSets {
            commonTest {
                dependencies {
                    implementation(project(":runtime:testing"))
                }
            }
        }
    }
}
