description = "HTTP Core for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: HTTP Core"
extra["moduleName"] = "software.aws.clientrt.http"

val ktorVersion: String by project

kotlin {

    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":client-runtime:utils"))
                implementation(project(":client-runtime:io"))
                // for Pipeline abstraction which already supports suspend functions
                api("io.ktor:ktor-utils:$ktorVersion")
            }
        }

        jvmMain {
            dependencies {
                api("io.ktor:ktor-utils-jvm:$ktorVersion")
            }
        }
    }
}
