/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */
// buildscript {
//     val atomicFuVersion: String by project
//     repositories {
//         mavenCentral()
//     }
//
//     dependencies {
//         classpath("org.jetbrains.kotlinx:atomicfu-gradle-plugin:$atomicFuVersion")
//     }
// }

// apply(plugin = "kotlinx-atomicfu")

description = "HTTP Core for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: HTTP Core"
extra["moduleName"] = "software.aws.clientrt.http"

val atomicFuVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":client-runtime:client-rt-core"))
                // exposes: Attributes
                api(project(":client-runtime:utils"))
                // exposes: service+middleware
                api(project(":client-runtime:io"))
                implementation(project(":client-runtime:logging"))

                implementation("org.jetbrains.kotlinx:atomicfu:$atomicFuVersion")
            }
        }

        commonTest {
            dependencies {
                implementation(project(":client-runtime:testing"))
            }
        }
    }
}