/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

description = "Logging primitives for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Logging"
extra["moduleName"] = "software.aws.clientrt.logging"

val ktorVersion: String by project

kotlin {
    explicitApi()
    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":client-runtime:utils"))
            }
        }
        jvmMain {
            dependencies {
                api("org.slf4j:slf4j-api:1.7.29")
            }
        }
        jvmTest {
            dependencies {
                implementation(kotlin("test"))
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.12")
                implementation("org.mockito:mockito-all:1.10.19")
                implementation("org.apache.logging.log4j:log4j-api:2.11.1")
                implementation("org.apache.logging.log4j:log4j-core:2.11.1")
                implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.13.3")
            }
        }
    }
}
