description = "Serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde"
extra["moduleName"] = "software.aws.clientrt.serde"
