blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/smithy-lang/smithy-kotlin/discussions/new/choose
    about: Please ask and answer questions as a discussion thread