/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

description = "OkHttp 4.x Client Engine for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: HTTP :: Engine :: OkHttp4"
extra["moduleName"] = "aws.smithy.kotlin.runtime.http.engine.okhttp4"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":runtime:protocol:http-client"))
                implementation(project(":runtime:protocol:http-client-engines:http-client-engine-okhttp"))
                implementation(libs.okhttp4)
            }
        }
        commonTest {
            dependencies {
                implementation(libs.kotlinx.coroutines.test)
            }
        }

        jvmTest {
            dependencies {
                implementation(project(":runtime:testing"))
                // use otel testing capabilities
                implementation(project(":runtime:observability:telemetry-provider-otel"))
                implementation(libs.opentelemetry.sdk.testing)
            }
        }

        all {
            languageSettings.optIn("aws.smithy.kotlin.runtime.InternalApi")
        }
    }
}

configurations.all {
    resolutionStrategy {
        force("com.squareup.okhttp3:okhttp:4.12.0")
    }
}
