/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

description = "Hashing functions for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Hashing"
extra["moduleName"] = "aws.smithy.kotlin.runtime.hashing"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":runtime:utils"))
            }
        }

        all {
            languageSettings.optIn("aws.smithy.kotlin.runtime.util.InternalApi")
        }
    }
}
