/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

description = "JSON serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde :: JSON"
extra["moduleName"] = "software.aws.clientrt.serde.json"

val gsonVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":client-runtime:serde"))
            }
        }
        jvmMain {
            dependencies {
                implementation("com.google.code.gson:gson:$gsonVersion")
            }
        }
    }
}
