description = "Serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde"
extra["moduleName"] = "software.aws.clientrt.serde-json"

kotlin {
    sourceSets {
        jvmMain {
            dependencies {
                implementation(project(":client-runtime:serde"))
                implementation("com.google.code.gson:gson:2.8.5")
            }
        }
    }
}
