/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
description = "Client runtime for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Client Runtime"
extra["moduleName"] = "aws.smithy.kotlin.runtime.client"

val coroutinesVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":runtime:runtime-core"))
                api(project(":runtime:auth:identity-api"))
            }
        }
        commonTest {
            dependencies {
                api(libs.kotlinx.coroutines.test)
                implementation(project(":runtime:testing"))
            }
        }

        all {
            languageSettings.optIn("aws.smithy.kotlin.runtime.InternalApi")
        }
    }
}
