/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

description = "IO primitives for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: IO"
extra["moduleName"] = "aws.smithy.kotlin.runtime.io"

val ktorVersion: String by project
val coroutinesVersion: String by project
val okioVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":runtime:utils"))

                implementation("com.squareup.okio:okio:$okioVersion")

                // FIXME - drop when done with refactor
                implementation("io.ktor:ktor-io:$ktorVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
            }
        }

        commonTest {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion")
                implementation(project(":runtime:testing"))
            }
        }

        jvmMain {
            dependencies {
                // file channel utils
                implementation("io.ktor:ktor-utils:$ktorVersion")
            }
        }

        all {
            languageSettings.optIn("aws.smithy.kotlin.runtime.util.InternalApi")
        }
    }
}
