description = "XML serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde :: XML"
extra["moduleName"] = "software.aws.clientrt.serde.xml"

val xmlpullVersion: String by project
val xpp3Version: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":client-runtime:serde"))
            }
        }
        jvmMain {
            dependencies {
                implementation("xmlpull:xmlpull:$xmlpullVersion")
                // https://mvnrepository.com/artifact/org.ogce/xpp3
                implementation("org.ogce:xpp3:$xpp3Version")
            }
        }
    }
}
