description = "XML serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde :: XML"
extra["moduleName"] = "software.aws.clientrt.serde.xml"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":client-runtime:serde"))
            }
        }
        jvmMain {
            dependencies {
                implementation("xmlpull:xmlpull:1.1.3.1")
                // https://mvnrepository.com/artifact/org.ogce/xpp3
                implementation("org.ogce:xpp3:1.1.6")
            }
        }
    }
}
