description = "Client runtime for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Client Runtime"
extra["moduleName"] = "software.amazon.smithy.kotlin.runtime"


kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":client-runtime:io"))
            }
        }
    }
}
