/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

description = "IO primitives for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: IO"
extra["moduleName"] = "software.aws.clientrt.io"

val ktorVersion: String by project
val coroutinesVersion: String by project

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":client-runtime:utils"))
                implementation("io.ktor:ktor-io:$ktorVersion")

                // Dispatchers.IO
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
            }
        }

        commonTest {
            dependencies {
                implementation(project(":client-runtime:testing"))
            }
        }

        jvmMain {
            dependencies {
                // file channel utils
                implementation("io.ktor:ktor-utils:$ktorVersion")
            }
        }
    }
}
