# Copied and modified from continuous-integration.yml

name: CI w/ reduced CRT Kotlin

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ci-reduced-pr-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  jvm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 17
          - 21
    steps:
      - name: Set start timestamp
        id: start
        run: printf 'timestamp=%(%s)T\n' >> "$GITHUB_OUTPUT"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Setup kat
        uses: aws/aws-kotlin-repo-tools/.github/actions/setup-kat@main

      - name: Checkout smithy-kotlin
        uses: actions/checkout@v4

      - name: Configure Gradle (Smithy Kotlin)
        uses: aws/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

      - name: Checkout aws-crt-kotlin
        uses: aws/aws-kotlin-repo-tools/.github/actions/checkout-head@main
        with:
          path: 'aws-crt-kotlin' # '.' would make this a sibling, and include build. Overriding reduced JAR dependency.
          repository: 'aws/aws-crt-kotlin'
          submodules: 'true'

      - name: Configure Gradle (CRT Kotlin)
        uses: aws/aws-kotlin-repo-tools/.github/actions/configure-gradle@main
        with:
          working-directory: './aws-crt-kotlin'

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'

      - name: Enable JAR reduction & disable Kotlin Native
        uses: aws/aws-kotlin-repo-tools/.github/actions/utils/add-to-local-properties@proguard-testing
        with:
          working-directory: '~/.sdkdev'
          addition: 'aws.kotlin.native = false\naws.sdk.proguard = true'

      - name: Publish reduced CRT Kotlin to Maven Local
        working-directory: './aws-crt-kotlin'
        run: |
          ./gradlew publishToMavenLocal # publish full size and reduced JARs
          ./gradlew replaceMavenLocalFullSizeJars # reduce JARs become the default

      # The checked out CRT Kotlin version might be a SNAPSHOT version e.g. in cross repo features (and include builds are off).
      - name: Depend on checked out CRT Kotlin version
        run: |
          cd aws-crt-kotlin
          version=$(kat get-property sdkVersion)
          echo "Found CRT version: $result"
          
          cd ..
          kat bump-version --file gradle/libs.versions.toml --version $version --property crt-kotlin-version

      - name: Build and Test Smithy Kotlin on JVM (with dependency on reduced CRT Kotlin)
        run: |
          ./gradlew -Ptest.java.version=${{ matrix.java-version }} jvmTest --stacktrace

      - name: Calculate duration
        id: end
        if: always()
        run: |
          printf -v now '%(%s)T'
          duration=$(( now - ${{ steps.start.outputs.timestamp }} ))
          echo "duration=$duration" >> "$GITHUB_OUTPUT"

      - name: Emit metrics
        if: always()
        uses: aws/aws-kotlin-repo-tools/.github/actions/emit-metrics@main
        with:
          namespace: CI Metrics
          dimensions: |
            Product=smithy-kotlin
            JobName=${{ github.job }}(${{ matrix.java-version }})-reduced
            Branch=${{ github.base_ref || github.ref_name }}
          metrics: |
            WorkflowSucceeded:${{ job.status == 'success' && '1' || '0' }}:Count
            WorkflowDuration:${{ steps.end.outputs.duration }}:Seconds
