name: Minor version bump check
on:
  pull_request:

jobs:
  minor-version-bump-check:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          # Only continue on branches starting with vX.X (e.g. v1.2, v1.2.3, v1.2-main)
          if [[ ! "$GITHUB_HEAD_REF" =~ ^v\.[0-9]+\.[0-9]+.*$ ]]; then
            exit 0
          fi

      - name: Minor version bump check
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/minor-version-bump@main
