name: Release readiness (snapshot dependency)

# Makes sure that we aren't relying on SNAPSHOT/dev versions of aws-crt-kotlin before merging
# Otherwise we could forget because the rest of CI is masking it

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-readiness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure Gradle
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

      - name: Configure error message
        run: echo "ERROR_MESSAGE=WARNING aws-crt-kotlin release and version bump might be required before merging!" >> $GITHUB_ENV

      - name: Build smithy-kotlin
        run: ./gradlew test jvmTest || echo $ERROR_MESSAGE
