name: Sync Mirror

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # TODO: REMOVE v
  pull_request:
    branches: [ main ]
  # TODO: REMOVE ^

jobs:
  git-sync:
    if: github.repository == 'smithy-lang/smithy-kotlin'
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.CI_USER }}:${{ secrets.CI_USER_PAT }}@github.com/smithy-lang/smithy-kotlin.git"
          source_branch: "main"
          destination_repo: "https://${{ secrets.CI_USER }}:${{ secrets.CI_USER_PAT }}@github.com/${{ secrets.GIT_SYNC_DESTINATION_REPO }}.git"
          destination_branch: "main"