name: Sync Mirror

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # TODO: REMOVE v
  pull_request:
    branches: [ main ]
  # TODO: REMOVE ^

jobs:
  git-sync:
    if: github.repository == 'smithy-lang/smithy-kotlin'
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "smithy-lang/smithy-kotlin"
          source_branch: "main"
          destination_repo: ${{ secrets.GIT_SYNC_DESTINATION_REPO }}
          destination_branch: "main"
          # destination_ssh_private_key:  ${{ secrets.GIT_SYNC_DESTINATION_SSH_PRIVATE_KEY }}